services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile.dev
    volumes:
      - ./gateway:/app
      - /app/node_modules

  inventarios:
    build:
      context: ./inventarios
      dockerfile: Dockerfile.dev
    volumes:
      - ./inventarios:/app
      - /app/node_modules

  ordenes:
    build:
      context: ./ordenes
      dockerfile: Dockerfile.dev
    volumes:
      - ./ordenes:/app
      - /app/node_modules
